config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token
from staff_management.applicant.views import HomeView
urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("", HomeView.as_view(), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("staff_management.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),

    # Your stuff: custom urls includes go here
     path("applicant/", include("staff_management.applicant.urls", namespace="applicants")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

staff_management/applicant/urls.py
from django.urls import path,re_path
from django.conf import settings
from django.conf.urls.static import static
# from staff_management.applicant.views import ApplicantCreateView #, ApplicantDetailsView 
from staff_management.applicant.views import ApplicantUpdateView, applicant_detail_view ,ApplicantUserListView,ApplicantUserJsonView

app_name = "applicant"
urlpatterns = [
    # path("detail/<int:id>", view=ApplicantCreateView.as_view(), name="detail"),
    path("update/", view=ApplicantUpdateView.as_view(), name="update"),
    path("detail/<int:id>/", view=applicant_detail_view, name="detail"),
	re_path(r'^app-user-list/', ApplicantUserListView.as_view(), name='app-user-list'),
	re_path(r'^appuser-list-json/$', ApplicantUserJsonView.as_view(), name='appuser-list-json'),

]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

staff_management/users/urls.py
from django.urls import path

from staff_management.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:id>/", view=user_detail_view, name="detail"),
]

staff_management/applicant/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from applicant.models import ApplicantUser,District,School

import datetime


class ApplicantUserUpdateForm(forms.ModelForm):


    # email = forms.EmailField(
    #     required=True,
    #     # choices=ApplicantUser.CHRONIC_CHOICES,
    #     widget=forms.Select(
    #         attrs={
    #             "class": "form-control formControl",
    #             "id": "email",
    #             'readonly':'readonly'
    #         }
    #     )
    # )
 
    dob = forms.DateField(
    widget=forms.SelectDateWidget(
        empty_label=("Choose Year", "Choose Month", "Choose Day"),
    ),
    )
    join_date = forms.DateField(
    widget=forms.SelectDateWidget(
        empty_label=("Choose Year", "Choose Month", "Choose Day"),
    ),
    )
    
    class Meta:
        model = ApplicantUser
        exclude=('age','experience','au_points','is_eligible')
        read_only=('email',)

    # first_name = forms.CharField(
    #     required=True,
    #     max_length=30,
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control formControl",
    #             "id": "first_name",
    #             "placeholder": "Enter First Name"
    #         }
    #     )
    # )
    # mobile = forms.CharField(
    #     required=False,
    #     max_length=30,
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control formControl",
    #             "id": "mobile",
    #             "placeholder": "Mobile Number"
    #         }

    #     )
    # )
    # aadhaar = forms.CharField(
    #     required=False,
    #     max_length=30,
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control formControl",
    #             "id": "aadhaar",
    #             "placeholder": "Aadhaar"
    #         }

    #     )
    # )


    # child_disease = forms.ChoiceField(
    #     required=True,
    #     choices=ApplicantUser.CHILD_DIS_CHOICES,
    #     widget=forms.Select(
    #         attrs={
    #             "class": "form-control formControl",
    #             "id": "child_disease"
    #         }
    #     )
    # )
 
    # disabled = forms.ChoiceField(
    #     required=True,
    #     choices=ApplicantUser.DIS_CHOICES,
    #     widget=forms.Select(
    #         attrs={
    #             "class": "form-control formControl",
    #             "id": "disabled"
    #         }
    #     )
    # )



    # gender = forms.ChoiceField(
    #     required=True,
    #     choices=ApplicantUser.GENDER_CHOICES,
    #     widget=forms.Select(
    #         attrs={
    #             "class": "form-control formControl",
    #             "id": "gender"
    #         }
    #     )
    # )
    # marial_status = forms.ChoiceField(
    #     required=True,
    #     choices=ApplicantUser.MARITAL_CHOICES,
    #     widget=forms.Select(
    #         attrs={
    #             "class": "form-control formControl",
    #             "id": "marital_status"
    #         }
    #     )
    # )

    # district = forms.ModelChoiceField(
    #     required=True,
    #     queryset=District.objects.all(),
    #     widget=forms.Select(
    #         attrs={
    #             "class": "form-control formControl standardSelect",
    #             "data-live-search": "true",
    #             "data-placeholder": "Select District"
    #         }
    #     )

    # )
    # school = forms.ModelChoiceField(
    #     required=True,
    #     queryset=School.objects.all(),
    #     widget=forms.Select(
    #         attrs={
    #             "class": "form-control formControl standardSelect",
    #             "data-live-search": "true",
    #             "data-placeholder": "Select State"
    #         }
    #     )

    # )
    # def clean_password(self):
    #     # Regardless of what the user provides, return the initial value.
    #     # This is done here, rather than on the field, because the
    #     # field does not have access to the initial value
    #     return self.initial["password"]



# class UserUpdateForm(forms.ModelForm):
#     first_name = forms.CharField(
#         required=True,
#         max_length=30,
#         widget=forms.TextInput(
#             attrs={
#                 "class": "form-control formControl",
#                 "id": "first_name",
#                 "placeholder": "Enter First Name"
#             }
#         )
#     )
#     last_name = forms.CharField(
#         required=True,
#         max_length=30,
#         widget=forms.TextInput(
#             attrs={
#                 "class": "form-control formControl",
#                 "id": "last_name",
#                 "placeholder": "Enter Last Name"
#             }
#         )
#     )
#     email = forms.CharField(
#         required=True,
#         max_length=300,
#         widget=forms.TextInput(
#             attrs={
#                 "class": "form-control formControl",
#                 "id": "email",
#                 "placeholder": "Enter Email",
#             }
#         )
#     )
#     password = forms.CharField(
#         required=False,
#         max_length=30,
#         widget=forms.PasswordInput(
#             attrs={
#                 "class": "form-control formControl",
#                 "id": "password",
#                 "placeholder": "Enter Password"
#             }

#         ),
#         help_text=("Raw passwords are not stored, so there is no way to see this user's password,"
#                    " but you can change the password")
#     )
#     mobile = forms.CharField(
#         required=True,
#         max_length=30,
#         widget=forms.TextInput(
#             attrs={
#                 "class": "form-control formControl",
#                 "id": "mobile",
#                 "placeholder": "Enter Mobile"
#             }
#         )
#     )

#     role = forms.ChoiceField(
#         required=True,
#         choices=Us_User.ROLE_CHOICES,
#         widget=forms.Select(
#             attrs={
#                 "class": "form-control formControl",
#             }
#         )
#     )

#     run_time_licenses = forms.ModelMultipleChoiceField(
#         required=False,
#         queryset=RunTimeLicense.objects.all(),
#         widget=forms.SelectMultiple(
#             attrs={
#                 "class": "form-control formControl standardSelect",
#                 "data-live-search": "true",
#                 "data-placeholder": "Select Run Time Licenses"
#             }
#         )
#     )


#     class Meta:
#         model = Us_User
#         fields = ['first_name', 'last_name', 'email', 'password', 'mobile', 'role',
#                   'status', 'run_time_licenses']

#     # def __init__(self, *args, **kwargs):
#     #     super().__init__(*args, **kwargs)
#     #     instance = kwargs.get('instance')
#     #     workshop = instance.workshop

#     #     if workshop:
#     #         # run_time_license_qs = workshop.run_time_licenses.all()
#     #         # self.fields['run_time_licenses'].queryset = run_time_license_qs
#     #         self.fields['report_to'].queryset = Us_User.objects.filter(
#     #             workshop=workshop).order_by('first_name')

#         # user_obj = instance.user
#         # if user_obj:
#         #     if not user_obj.is_superuser:
#         #         oem_obj = user_obj.us_user.oem or user_obj.oem
#         #         self.fields['user_models'].queryset = Model.objects.filter(oem=oem_obj)

staff_management/applicant/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
# Create your views here.
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views import View
from applicant.forms import ApplicantUserUpdateForm
from applicant.models import ApplicantUser
from django.views.generic import DetailView, RedirectView, UpdateView, CreateView,ListView
# from .mixins import GroupRequiredMixin
from applicant.helpers import PaginationHelper
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.db.models import Q
class HomeView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user_obj = request.user

        if user_obj.is_admin:
            print("admin_home")
            context = {'user':user_obj}
            return render(request, 'pages/admin_home.html', context)

        else:
            print("applicant_home")

            context = {'user':user_obj}
            return render(request, 'pages/applicant_home.html', context)

    def dispatch(self, *args, **kwargs):
        return super(HomeView, self).dispatch(*args, **kwargs)



class ApplicantDetailView(LoginRequiredMixin, DetailView):

    model = ApplicantUser

    slug_field = "id"
    slug_url_kwarg = "id"
    def get_context_data(self, **kwargs):
        context = super(ApplicantDetailView, self).get_context_data(**kwargs)
        context['form'] = ApplicantUserUpdateForm()
        return context


applicant_detail_view = ApplicantDetailView.as_view()

# class ApplicationUpdateView()
class ApplicantUpdateView(LoginRequiredMixin, UpdateView):

    model = ApplicantUser
    # fields = ["full_name"]
    fields = ['full_name','mobile',
    'aadhaar',
    'chronic_disease',
    'child_disease',
    'disabled',
    'gender',
    'dob',
    'marital_status',
    'district',
    'school',
    'join_date']
    def get_success_url(self):
        return reverse("applicant:detail", kwargs={"id": self.request.user.id})

    def get_object(self):
        # print(self.request.user)
        # import ipdb;ipdb.set_trace()
        return ApplicantUser.objects.get(id=self.request.user.id)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)




class ApplicantUserBaseView( View, PaginationHelper):

    """
    Base view for Flash
    """
    group_required = ['fauthor', 'sadmin']

    def get_app_user(self):
        return get_object_or_404(
            ApplicantUser.objects.all(),
            pk=self.kwargs.get('id')
        )


class ApplicantUserListView(View, PaginationHelper):
    """
    Flash Create View
    """

    def get(self, request, *args, **kwargs):

        app_user = self.paginate(request, ApplicantUser.objects.all())

        return render(
            request,
            'applicant/app_user_list.html',
            {
                'app_user': app_user,
            }
        )


class ApplicantUserJsonView(BaseDatatableView):
    """
    Model list view.
    """

    model = ApplicantUser
    columns = ['email',
    'full_name',
    'gender',
    'school',
    'au_points',
    'direct_eligible',
    'id'
    ]
    order_columns = [
        'au_points',
 
    ]

    def render_column(self, row, column):
        # We want to render user as a custom column
        if column == 'id':
            # escape HTML for security reasons
            return super(ApplicantUserJsonView, self).render_column(row, column)
        else:
            return super(ApplicantUserJsonView, self).render_column(row, column)

    def get_initial_queryset(self):
        
        return ApplicantUser.objects.filter(email__staff=False).filter(au_points__gt=0).order_by('-au_points')

    def filter_queryset(self, qs):
        # use parameters passed in GET request to filter queryset

        # simple example:
        search = self.request.GET.get('search[value]', None)
        if search:
            qs = qs.filter(
                Q(full_name__icontains=search) 

                # Q(year_model_year__icontains=search)
            )
        return qs

staff_management/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "email"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

staff_management/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User

    slug_field = "id"
    slug_url_kwarg = "id"



user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["full_name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"id": self.request.user.id})

    def get_object(self):
        return User.objects.get(email=self.request.user.email)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"id": self.request.user.id})


user_redirect_view = UserRedirectView.as_view()

staff_management/templates/applicant/app_user_list.html
{% load static %}
{% block content %}
<div class="content mt-3">
  <div class="animated fadeIn">
    <div class="row">
      <div class="col-lg-12" id="">
        <div class="card">
          <div class="card-header">
            <strong class="card-title">Application List</strong>
            <div class="pull-right">
            
            </div>
          </div>
          <div class="card-body">
            <div>

            </div>



            <table class="table table-striped table-bordered dataTables_wrapper" id="app_user" style="width:100%"
              data-url="{% url 'applicant:appuser-list-json' %}">
              <thead class="thead-blue">
                <tr style="color: black;">
                  <th scope="col">email</th>
                  <th scope="col">full_name</th>
                  <th scope="col">gender</th>
                  <th scope="col">school</th>
                  <th scope="col">au_points</th>
                  <th scope="col">direct_eligible</th>
                
    
                </tr>
              </thead>
              <tbody>

              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div><!-- .animated -->
</div>
{% endblock %}

staff_management/templates/applicant/applicantuser_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}User: {{ object.email }}{% endblock %}

{% block content %}
<!-- <form method="post" class="uniForm"> -->
   
        <div class="col-sm-8">
            <div class="container mb-5">
                <h4 class="mt-3">User Details Preview.</h4>
                <div class="mt-5 p-3 shadow">
                    <form>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="firstname">Email:</label>
                              
                            </div>
                            <div class="form-group col-md-6">
                                <label for="lastname">{{object.email}}</label>
                                <!-- <input type="text" class="form-control" id="lastname" placeholder="Last Name"> -->
                               
                            </div>
                        </div>
						<div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="firstname">Full Name:</label>
                                
                            </div>
                            <div class="form-group col-md-6">
                                <label for="lastname">{{object.full_name}}</label>
                      
                             
                            </div>
                         </div>  




                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="firstname">Aadhar:</label>
                               
                            </div>
                            <div class="form-group col-md-6">
                                <label for="lastname">{{object.aadhaar}}</label>
                                <!-- <input type="text" class="form-control" id="lastname" placeholder="Last Name"> -->
                               
                            </div>
                        </div>
						<div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="firstname">Gender:</label>
                                
                            </div>
                            <div class="form-group col-md-6">
                                <label for="lastname">{{object.gender}}</label>
                      
                             
                            </div>
                         </div> 

						<div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="firstname">Marital Status:</label>
                               
                            </div>
                            <div class="form-group col-md-6">
                                <label for="lastname">{{object.marital_status}}</label>
                      
                             
                            </div>
                         </div> 


						<div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="firstname">Chronic Disease:</label>
                           
                            </div>
                            <div class="form-group col-md-6">
                                <label for="lastname">{{object.chronic_disease}}</label>
                      
                             
                            </div>
                         </div> 
						<div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="firstname">Is Child Diseased(i.e. Thalasemia):</label>
                       
                            </div>
                            <div class="form-group col-md-6">
                                <label for="lastname">{{object.child_disease}}</label>
                      
                             
                            </div>
                         </div> 
						<div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="firstname">Is Disabled</label>
                                
                            </div>
                            <div class="form-group col-md-6">
                                <label for="lastname">{{object.disabled}}</label>
                      
                             
                            </div>
                         </div> 
						<div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="firstname">DOB</label>
                                
                            </div>
                            <div class="form-group col-md-6">
                                <label for="lastname">{{object.dob}} (age :{{object.age}})</label>
                      
                            </div>
                         </div> 

						<div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="firstname">District</label>
                                
                            </div>
                            <div class="form-group col-md-6">
                                <label for="lastname">{{object.district}}</label>
                      
                             
                            </div>
                         </div> 
						<div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="firstname">School</label>
                       
                            </div>
                            <div class="form-group col-md-6">
                                <label for="lastname">{{object.school}}</label>
                      
                             
                            </div>
                         </div> 



                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="firstname">Join Date:</label>
                  
                            </div>
                            <div class="form-group col-md-6">
                                <label for="lastname">{{object.join_date}} (Experience:{{object.experience}})</label>
                                <!-- <input type="text" class="form-control" id="lastname" placeholder="Last Name"> -->
                               
                            </div>
                        </div>
						<div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="firstname">Points:</label>
                 
                            </div>
                            <div class="form-group col-md-6">
                                <label for="lastname">{{object.au_points}}</label>
                      
                             
                            </div>
                         </div> 









                        <!-- <button type="submit" class="btn btn-primary">Register</button> -->
                    </form>

                </div>
            </div>
        </div>





{% endblock content %}



{% block footer_javascript %}
<!-- <script src="{% static 'js/us_users/us_user_update.js' %}"></script> -->

{% endblock %}

staff_management/templates/applicant/applicantuser_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.email }}{% endblock %}

{% block content %}
  <h1>{{ user.email }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'applicant:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}
{% block footer_javascript %}
<script type="text/javascript">
   document.getElementsByName("email").disabled=true;
</script>>
{% endblock %}